### ISSUE TITLE
Needs testing

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/windspharm-feedstock#1]
@jakirkham do you own a Mac? Can you test this package for me please? (Just install, import, and run `run_test.sh`.)

**Comment by ajdawson** [comment]
I tested this on osx 10.11 for Python 2.7 and it works OK I think. In fairness though it is a pure Python module unlikely to fail. You probably want to focus more on pyspharm.

**Comment by ocefpaf** [comment]
> You probably want to focus more on pyspharm.

Thank you. Since I don't own a Mac and our CIs report that everything is OK I want to reproduce a end user experience, that is, use `windspharm` and its call to `pyspharm`.

**Comment by ajdawson** [comment]
That's fair. I've installed from conda-forge on an OS X 10.11 (El Capitan) machine, for Python 2.7, 3.4 and 3.5 and all the tests pass so I think we are safe on this.

Sorry for being harsh before @ocefpaf, let's be friends :smile:! You did a nice job of setting up the build here. My plan had been to get a conda-forge build organised to coincide with the next release of windspharm so I could smoothly transition all documentation to reference the conda-forge build instead of my own channel. I'm totally on board with using conda-forge, just not quite ready to make this the "official" release channel if you know what I mean, which is why I'm keen to make sure my own builds are functional instead of directing people straight here.

**Comment by ocefpaf** [comment]
> Sorry for being harsh before @ocefpaf, let's be friends :smile:! 

Your repo your rules. I never took that comment as harsh nor that you were working against me/us.

Conda-forge is a community place and your presence here is very welcomed!

**Comment by ocefpaf** [comment]
Including https://github.com/conda-forge/windspharm-feedstock/issues/1#issuecomment-209366143 I've got another 2 additional independent tests for `pyspharm`+`windspharm` on OS X. Closing this.

**Comment by jakirkham** [comment]
Sorry I missed out on this one. Glad you guys got it sorted.

**Comment by ocefpaf** [comment]
> Sorry I missed out on this one. Glad you guys got it sorted.

Thanks @jakirkham. (Now I have 2 more OS X volunteers :wink:)
